# coding: utf-8

"""
    HRC API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_db_request(self):
        """Test case for create_db_request

        """
        pass

    def test_create_edge_by_keys(self):
        """Test case for create_edge_by_keys

        """
        pass

    def test_create_node_by_key(self):
        """Test case for create_node_by_key

        """
        pass

    def test_delete_edge_by_keys(self):
        """Test case for delete_edge_by_keys

        """
        pass

    def test_delete_node_by_key(self):
        """Test case for delete_node_by_key

        """
        pass

    def test_get_descendants(self):
        """Test case for get_descendants

        """
        pass

    def test_get_node_by_key(self):
        """Test case for get_node_by_key

        """
        pass

    def test_parse_payload(self):
        """Test case for parse_payload

        """
        pass

    def test_patch_node_by_key(self):
        """Test case for patch_node_by_key

        """
        pass

    def test_put_node_by_key(self):
        """Test case for put_node_by_key

        """
        pass


if __name__ == '__main__':
    unittest.main()
