# coding: utf-8

"""
    HRC API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Node(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'metadata': 'str',
        'hrc_rul': 'str'
    }

    attribute_map = {
        'key': 'key',
        'metadata': 'metadata',
        'hrc_rul': 'hrc-rul'
    }

    def __init__(self, key=None, metadata=None, hrc_rul=None):  # noqa: E501
        """Node - a model defined in Swagger"""  # noqa: E501

        self._key = None
        self._metadata = None
        self._hrc_rul = None
        self.discriminator = None

        self.key = key
        if metadata is not None:
            self.metadata = metadata
        if hrc_rul is not None:
            self.hrc_rul = hrc_rul

    @property
    def key(self):
        """Gets the key of this Node.  # noqa: E501


        :return: The key of this Node.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this Node.


        :param key: The key of this Node.  # noqa: E501
        :type: str
        """
        if key is None:
            raise ValueError("Invalid value for `key`, must not be `None`")  # noqa: E501

        self._key = key

    @property
    def metadata(self):
        """Gets the metadata of this Node.  # noqa: E501


        :return: The metadata of this Node.  # noqa: E501
        :rtype: str
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this Node.


        :param metadata: The metadata of this Node.  # noqa: E501
        :type: str
        """

        self._metadata = metadata

    @property
    def hrc_rul(self):
        """Gets the hrc_rul of this Node.  # noqa: E501


        :return: The hrc_rul of this Node.  # noqa: E501
        :rtype: str
        """
        return self._hrc_rul

    @hrc_rul.setter
    def hrc_rul(self, hrc_rul):
        """Sets the hrc_rul of this Node.


        :param hrc_rul: The hrc_rul of this Node.  # noqa: E501
        :type: str
        """

        self._hrc_rul = hrc_rul

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Node, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Node):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
